# NumPy

### Basic Array Operations with NumPy

In [3]:
import numpy as np

In [10]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [1, 2, 3]])

# display array
print(arr1, end="\n\n")

# add arrays
print(arr1 + arr2, end="\n\n")

# subtract arrays
print(arr2 - arr1, end="\n\n")

[[1 2 3]
 [4 5 6]]

[[ 8 10 12]
 [ 5  7  9]]

[[ 6  6  6]
 [-3 -3 -3]]



In [28]:
arr = np.array([1, 2, 3, 4, 5])

# slicing in arrays
print(arr[2:7:2])
print(arr[2:7:2] + 2)

# creating a copy of a numpy array
dup = arr.copy()
print(dup)

[3 5]
[5 7]
[1 2 3 4 5]


In [29]:
# Array Properties

print("No of dimensions: ", arr.ndim)
print("Shape: ", arr.shape)
print("No of elements along an axis: ", arr.size)

No of dimensions:  1
Shape:  (5,)
No of elements along an axis:  5


In [32]:
# Transpose of array

transpose = arr1.transpose()
print(arr1)
print(transpose)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [45]:
# Join arrays
a1 = np.array([1, 2, 3])
a2 = np.array([4, 5, 6])
result = np.concatenate((a1, a2))
print(result)

# Split Array
print(np.vsplit(arr1, 2))

[1 2 3 4 5 6]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


### Linear Algebra with NumPy

In [56]:
import numpy.linalg as linalg

In [76]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])

In [54]:
# @ operator in numpy - matrix multiplication

print(arr1 @ arr2)
print(np.matmul(arr1, arr2)) # same as @

[[ 1  2  4]
 [ 4  5 10]
 [ 7  8 16]]
[[ 1  2  4]
 [ 4  5 10]
 [ 7  8 16]]


In [63]:
# QR Decomposition

Q, R = linalg.qr(arr1)
print(Q)
print(R)

print("original: \n", Q @ R)

[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]
original: 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [64]:
# finding eigen values of a general matrix

print(linalg.eigvals(arr1))

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [68]:
# calculating determinant of matrix

print(arr1, "\n determinant: ", linalg.det(arr1))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 determinant:  0.0


In [72]:
# solving 2 linear equations with linalg.solve()
# 2x + 3y = 35
# x + y = 14
# ans: x = 7, y = 7

coeff = np.array([[2, 3], [1, 1]]) # coefficient matrix
const = np.array([35, 14])         # constant matrix
ans = linalg.solve(coeff, const)
print(ans)

[7. 7.]


In [78]:
# inverse of a matrix
# inverse can be found only of a singular matrix

arr = linalg.inv(arr2)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [82]:
arr = linalg.diagonal(arr1)
print(arr)

[1 5 9]


In [80]:
arr = linalg.matrix_transpose(arr1)
print(arr)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Polynomials with NumPy

In [83]:
import numpy.polynomial as poly

In [88]:
# x^2 - 9x + 20
# zeroes of the quadration eqn = 4, 5

coeff = [1, -9, 20]

x = 5
ans = np.polyval(coeff, x)
print(ans)

x = 4
ans = np.polyval(coeff, x)
print(ans)

0
0


In [94]:
coeff1 = [1, -9, 20]
coeff2 = [1, -8, 16]

print("Addition: ", np.polyadd(coeff1, coeff2))
print("Subtraction: ", np.polysub(coeff1, coeff2))
print("Multiplication: ", np.polymul(coeff1, coeff2))
print("Division: ", np.polydiv(coeff1, coeff2))

Addition:  [  2 -17  36]
Subtraction:  [ 0 -1  4]
Multiplication:  [   1  -17  108 -304  320]
Division:  (array([1.]), array([-1.,  4.]))


In [98]:
print("Differentiation: \n", np.polyder(coeff1))
print("Integration: \n", np.polyint(coeff2))

Differentiation: 
 [ 2 -9]
Integration: 
 [ 0.33333333 -4.         16.          0.        ]


# Pandas

In [101]:
import pandas as pd

In [102]:
df = pd.read_csv("Student_Performance_Dataset.csv")

In [103]:
print(df)

     Student_ID  Age  Gender  Class  Study_Hours_Per_Day  \
0         S0001   15    Male     12                  1.0   
1         S0002   19  Female      9                  1.6   
2         S0003   14  Female     12                  3.6   
3         S0004   18  Female      9                  5.5   
4         S0005   14    Male     10                  5.0   
...         ...  ...     ...    ...                  ...   
4995      S4996   17    Male     11                  4.0   
4996      S4997   19    Male     10                  5.6   
4997      S4998   16  Female      9                  2.3   
4998      S4999   15    Male     11                  2.9   
4999      S5000   19  Female     10                  2.0   

      Attendance_Percentage Parental_Education Internet_Access  \
0                        65       Postgraduate              No   
1                        58           Graduate              No   
2                        64        High School             Yes   
3              

In [104]:
print(df.columns)

Index(['Student_ID', 'Age', 'Gender', 'Class', 'Study_Hours_Per_Day',
       'Attendance_Percentage', 'Parental_Education', 'Internet_Access',
       'Extracurricular_Activities', 'Math_Score', 'Science_Score',
       'English_Score', 'Previous_Year_Score', 'Final_Percentage',
       'Performance_Level', 'Pass_Fail'],
      dtype='object')


In [105]:
print(df.dtypes)

Student_ID                     object
Age                             int64
Gender                         object
Class                           int64
Study_Hours_Per_Day           float64
Attendance_Percentage           int64
Parental_Education             object
Internet_Access                object
Extracurricular_Activities     object
Math_Score                      int64
Science_Score                   int64
English_Score                   int64
Previous_Year_Score             int64
Final_Percentage              float64
Performance_Level              object
Pass_Fail                      object
dtype: object
